# Generated by Django 4.0.4 on 2022-04-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name user')),
                ('login', models.CharField(max_length=30, verbose_name='name user')),
                ('email_address', models.EmailField(max_length=254, verbose_name='name user')),
                ('status', models.CharField(max_length=10, verbose_name='status user')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name license')),
                ('secret', models.CharField(max_length=100, verbose_name='Secret key')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='app_scripts.client', verbose_name='Client')),
            ],
            options={
                'db_table': 'clients_license',
            },
        ),
    ]
