name: scripts_base
env:
  DOCKER_USER: "deskent"
  DOCKER_REPOSITORY_NAME: "deskent"
  PROJECT_NAME: "scripts_base"
  STAGE: "dev"
  VERSION: "ver-${{ github.sha }}"
  COUNT: "1.0"
on:
  push:
    branches: [ deskent111 ]
jobs:
  create_docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u $DOCKER_USER --password-stdin
      - name: Docker build
        run: |
          docker build --no-cache . -t ${{ env.PROJECT_NAME }}:${{ env.VERSION }}
      - name: Docker tagging
        run: |
          docker tag ${{ env.PROJECT_NAME }}:${{ env.VERSION}} ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.PROJECT_NAME}}-${{ env.COUNT }}
      - name: Docker push
        run: |
          docker push ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.PROJECT_NAME}}-${{ env.COUNT }}
  deploy:
    runs-on: ubuntu-latest
    needs: [create_docker_build]
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd "/home/${{ secrets.USERNAME }}/deploy/${{ env.PROJECT_NAME }}/${{ env.STAGE }}"
            docker-compose -f docker-compose-${{ env.PROJECT_NAME}}-${{ env.STAGE }}.yml down
            docker rmi ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.PROJECT_NAME}}-${{ env.COUNT }}
            docker-compose -f docker-compose-${{ env.PROJECT_NAME}}-${{ env.STAGE }}.yml up -d --build
